<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\QuantTrading.Application\QuantTrading.Application.csproj" />
    <ProjectReference Include="..\QuantTrading.Domain\QuantTrading.Domain.csproj" />
  </ItemGroup>

</Project>
