// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuantTrading.Infrastructure;

#nullable disable

namespace QuantTrading.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525122204_modification-on-BacktestResult-and-added-TradeResult")]
    partial class modificationonBacktestResultandaddedTradeResult
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuantTrading.Domain.Entities.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CashBalance")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("QuantTrading.Domain.Entities.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AverageEntryPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("PortfolioId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("QuantTrading.Domain.Entities.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<int>("Side")
                        .HasColumnType("integer");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("QuantTrading.Domain.Models.BacktestResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("BacktestResults");
                });

            modelBuilder.Entity("QuantTrading.Domain.Models.TradeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BacktestResultId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EnteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ExitPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("ExitedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("RealizedPnL")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BacktestResultId");

                    b.ToTable("TradeRecords");
                });

            modelBuilder.Entity("QuantTrading.Domain.Entities.Position", b =>
                {
                    b.HasOne("QuantTrading.Domain.Entities.Portfolio", null)
                        .WithMany("Positions")
                        .HasForeignKey("PortfolioId");
                });

            modelBuilder.Entity("QuantTrading.Domain.Models.BacktestResult", b =>
                {
                    b.OwnsOne("QuantTrading.Domain.ValueObjects.Money", "FinalCapital", b1 =>
                        {
                            b1.Property<Guid>("BacktestResultId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("FinalCapitalAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("FinalCapitalCurrency");

                            b1.HasKey("BacktestResultId");

                            b1.ToTable("BacktestResults");

                            b1.WithOwner()
                                .HasForeignKey("BacktestResultId");
                        });

                    b.OwnsOne("QuantTrading.Domain.ValueObjects.Money", "GrossLoss", b1 =>
                        {
                            b1.Property<Guid>("BacktestResultId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("GrossLossAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("GrossLossCurrency");

                            b1.HasKey("BacktestResultId");

                            b1.ToTable("BacktestResults");

                            b1.WithOwner()
                                .HasForeignKey("BacktestResultId");
                        });

                    b.OwnsOne("QuantTrading.Domain.ValueObjects.Money", "GrossProfit", b1 =>
                        {
                            b1.Property<Guid>("BacktestResultId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("GrossProfitAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("GrossProfitCurrency");

                            b1.HasKey("BacktestResultId");

                            b1.ToTable("BacktestResults");

                            b1.WithOwner()
                                .HasForeignKey("BacktestResultId");
                        });

                    b.OwnsOne("QuantTrading.Domain.ValueObjects.Money", "InitialCapital", b1 =>
                        {
                            b1.Property<Guid>("BacktestResultId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("InitialCapitalAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("InitialCapitalCurrency");

                            b1.HasKey("BacktestResultId");

                            b1.ToTable("BacktestResults");

                            b1.WithOwner()
                                .HasForeignKey("BacktestResultId");
                        });

                    b.Navigation("FinalCapital")
                        .IsRequired();

                    b.Navigation("GrossLoss")
                        .IsRequired();

                    b.Navigation("GrossProfit")
                        .IsRequired();

                    b.Navigation("InitialCapital")
                        .IsRequired();
                });

            modelBuilder.Entity("QuantTrading.Domain.Models.TradeRecord", b =>
                {
                    b.HasOne("QuantTrading.Domain.Models.BacktestResult", null)
                        .WithMany()
                        .HasForeignKey("BacktestResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuantTrading.Domain.Entities.Portfolio", b =>
                {
                    b.Navigation("Positions");
                });
#pragma warning restore 612, 618
        }
    }
}
